import { useMemo, useState } from 'react';
import { Users, Building2, FolderKanban, Heart, Clock3, Download, RotateCcw, Check, Search, ChevronLeft, ChevronRight, ArrowDownUp, ExternalLink } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { DashboardShell } from '@/components/dashboard-shell';
import { departments, hrProjects, initialHrFilters, filterHr, summarizeHr, hrCsv, type HrFilters } from '@/lib/hr-data';
import { number } from '@/lib/sales-data';

const referenceUrl = 'https://github.com/Rafael-TOZATO/dashboard-gestao-recursos-humanos-dio-santander-main';
function HrSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return <div className="filter"><label>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger className="filter-trigger" aria-label={label}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{label === 'Departamento' ? 'Todos os departamentos' : label === 'Projeto' ? 'Todos os projetos' : 'Todos'}</SelectItem>{options.map(o => <SelectItem value={o} key={o}>{o}</SelectItem>)}</SelectContent></Select></div>;
}
function HrTip({ active, payload, label, unit = '' }: { active?: boolean; payload?: { name?: string; value?: number; payload?: { name?: string } }[]; label?: string; unit?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="chart-tip"><p>{label || payload[0]?.payload?.name}</p>{payload.map((p,i) => <strong key={i}>{p.name}: {number(p.value ?? 0)} {unit}</strong>)}</div>;
}
const axisTick = { fill: 'var(--muted-foreground)', fontSize: 10 };
export function HrDashboard() {
  const [filters, setFilters] = useState<HrFilters>(initialHrFilters);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const [sort, setSort] = useState<'id' | 'salary' | 'hours' | 'dependents'>('id');
  const [descending, setDescending] = useState(false);
  const [exported, setExported] = useState(false);
  const [projectMetric, setProjectMetric] = useState<'hours' | 'employees'>('hours');
  const data = useMemo(() => filterHr(filters), [filters]);
  const sums = summarizeHr(data);
  const update = (key: keyof HrFilters, value: string) => { setFilters(f => ({ ...f, [key]: value })); setPage(0); };
  const departmentData = departments.map(name => ({ name, employees: data.people.filter(e => e.department === name).length, Feminino: data.people.filter(e => e.department === name && e.sex === 'Feminino').reduce((s,e) => s + e.salary, 0), Masculino: data.people.filter(e => e.department === name && e.sex === 'Masculino').reduce((s,e) => s + e.salary, 0) })).filter(d => d.employees > 0);
  const projectData = hrProjects.map(name => ({ name, hours: data.work.filter(a => a.project === name).reduce((s,a) => s + a.hours, 0), employees: new Set(data.work.filter(a => a.project === name).map(a => a.employeeId)).size })).filter(p => p.employees > 0).sort((a,b) => b[projectMetric] - a[projectMetric]);
  const personRows = data.people.map(e => ({ ...e, hours: data.work.filter(a => a.employeeId === e.id).reduce((s,a) => s + a.hours, 0), projects: data.work.filter(a => a.employeeId === e.id).map(a => a.project) }));
  const tableRows = personRows.filter(e => `${e.id} ${e.department} ${e.sex} ${e.projects.join(' ')}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).sort((a,b) => (descending ? -1 : 1) * (sort === 'id' ? a.id.localeCompare(b.id) : a[sort] - b[sort]));
  const pageCount = Math.max(1, Math.ceil(tableRows.length / 5));
  const safePage = Math.min(page, pageCount - 1);
  const dependentsData = data.people.map(e => ({ name: e.id, dependents: e.dependents }));
  const sortBy = (key: typeof sort) => { if (sort === key) setDescending(d => !d); else { setSort(key); setDescending(key !== 'id'); } setPage(0); };
  const exportData = () => { const url = URL.createObjectURL(new Blob([hrCsv(data)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'atlas-recursos-humanos.csv'; a.click(); URL.revokeObjectURL(url); setExported(true); setTimeout(() => setExported(false), 2500); };
  const cards = [
    { label: 'Empregados', value: number(sums.employees), icon: Users, detail: 'Pessoas únicas' },
    { label: 'Departamentos', value: number(sums.departments), icon: Building2, detail: 'Na seleção atual' },
    { label: 'Projetos', value: number(sums.projects), icon: FolderKanban, detail: 'Com alocações' },
    { label: 'Dependentes', value: number(sums.dependents), icon: Heart, detail: 'Vinculados à equipe' },
    { label: 'Horas trabalhadas', value: `${number(sums.hours)} h`, icon: Clock3, detail: 'Alocações selecionadas' },
  ];
  return <DashboardShell view="hr">
    <div className="page-heading"><div><h1>Gestão de Recursos Humanos</h1><p className="subtitle">Pessoas, projetos e alocação <span className="mx-2">·</span>{filters.department === 'all' ? 'Todos os departamentos' : filters.department}</p></div><div className="page-actions flex gap-2"><Button variant="outline" className="action-button" onClick={() => { setFilters(initialHrFilters); setSearch(''); setPage(0); setSort('id'); setDescending(false); }}><RotateCcw />Redefinir</Button><Button className="action-button" onClick={exportData}>{exported ? <Check /> : <Download />}{exported ? 'Exportado' : 'Exportar CSV'}</Button></div></div>
    <div className="hr-reference"><ExternalLink size={13} /><span>Base demonstrativa reconstruída <span className="mx-1">·</span><a href={referenceUrl} target="_blank" rel="noopener noreferrer">Referência DIO · Santander</a></span></div>
    <div className="filters hr-filters"><HrSelect label="Departamento" value={filters.department} options={departments} onChange={v => update('department',v)} /><HrSelect label="Projeto" value={filters.project} options={hrProjects} onChange={v => update('project',v)} /><HrSelect label="Sexo" value={filters.sex} options={['Feminino','Masculino']} onChange={v => update('sex',v)} /></div>
    <div className="kpis hr-kpis">{cards.map(k => <article className="metric-card" key={k.label}><div className="metric-top">{k.label}<span className="metric-icon"><k.icon size={15} /></span></div><div className="metric-value">{k.value}</div><div className="metric-bottom">{k.detail}</div></article>)}</div>
    <div className="chart-grid">
      <section className="chart-section"><div className="section-heading"><div><h2>Empregados por departamento</h2><p className="section-meta">Distribuição da equipe · pessoas únicas</p></div><Building2 size={15} className="text-muted-foreground" /></div>{departmentData.length ? <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={departmentData} layout="vertical" margin={{ left: 8, right: 20 }}><CartesianGrid stroke="var(--border)" horizontal={false} strokeDasharray="3 5" /><XAxis type="number" allowDecimals={false} tick={axisTick} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={100} tick={axisTick} axisLine={false} tickLine={false} /><Tooltip content={<HrTip />} cursor={{ fill: 'var(--muted)' }} /><Bar dataKey="employees" name="Empregados" fill="var(--primary)" barSize={28} radius={[0,4,4,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <div className="hr-empty">Nenhuma alocação para os filtros selecionados.</div>}<div className="flex flex-wrap gap-1 mt-2">{departments.map(d => <Button size="sm" variant={filters.department === d ? 'secondary' : 'ghost'} key={d} onClick={() => update('department', filters.department === d ? 'all' : d)} aria-pressed={filters.department === d}>{d}</Button>)}</div></section>
      <section className="chart-section"><div className="section-heading"><div><h2>Alocação por projeto</h2><p className="section-meta">{projectMetric === 'hours' ? 'Horas registradas · h' : 'Pessoas por projeto'}</p></div><div className="flex gap-1"><Button size="sm" variant={projectMetric === 'hours' ? 'secondary' : 'ghost'} aria-pressed={projectMetric === 'hours'} onClick={() => setProjectMetric('hours')}>Horas</Button><Button size="sm" variant={projectMetric === 'employees' ? 'secondary' : 'ghost'} aria-pressed={projectMetric === 'employees'} onClick={() => setProjectMetric('employees')}>Pessoas</Button></div></div>{projectData.length ? <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={projectData} layout="vertical" margin={{ left: 0, right: 15 }}><CartesianGrid stroke="var(--border)" horizontal={false} strokeDasharray="3 5" /><XAxis type="number" tick={axisTick} allowDecimals={false} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={112} tick={axisTick} axisLine={false} tickLine={false} /><Tooltip content={<HrTip unit={projectMetric === 'hours' ? 'h' : ''} />} cursor={{ fill: 'var(--muted)' }} /><Bar dataKey={projectMetric} name={projectMetric === 'hours' ? 'Horas' : 'Pessoas'} fill="var(--chart-2)" barSize={17} radius={[0,3,3,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <div className="hr-empty">Nenhum projeto para a seleção.</div>}</section>
      <section className="chart-section"><div className="section-heading"><div><h2>Salário por departamento e sexo</h2><p className="section-meta">Total salarial · unidades monetárias demonstrativas</p></div></div>{departmentData.length ? <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={departmentData} margin={{ left: 0, right: 10 }}><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 5" /><XAxis dataKey="name" tick={axisTick} axisLine={false} tickLine={false} /><YAxis tick={axisTick} tickFormatter={v => `${v/1000} mil`} axisLine={false} tickLine={false} /><Tooltip content={<HrTip unit="u.m." />} cursor={{ fill: 'var(--muted)' }} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="Feminino" fill="var(--chart-2)" maxBarSize={35} radius={[3,3,0,0]} isAnimationActive={false} /><Bar dataKey="Masculino" fill="var(--primary)" maxBarSize={35} radius={[3,3,0,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <div className="hr-empty">Nenhum empregado para a seleção.</div>}</section>
      <section className="chart-section"><div className="section-heading"><div><h2>Dependentes por empregado</h2><p className="section-meta">Identificadores anônimos · {number(sums.dependents)} dependentes</p></div><Heart size={15} className="text-muted-foreground" /></div>{dependentsData.length ? <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={dependentsData} margin={{ left: -20, right: 10 }}><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 5" /><XAxis dataKey="name" tick={axisTick} axisLine={false} tickLine={false} interval={0} /><YAxis tick={axisTick} allowDecimals={false} axisLine={false} tickLine={false} /><Tooltip content={<HrTip />} cursor={{ fill: 'var(--muted)' }} /><Bar dataKey="dependents" name="Dependentes" fill="var(--chart-3)" maxBarSize={30} radius={[3,3,0,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <div className="hr-empty">Nenhum empregado para a seleção.</div>}</section>
    </div>
    <section className="table-section"><div className="section-heading"><div><h2>Detalhamento da equipe</h2><p className="section-meta">{number(data.people.length)} empregados · salário sem periodicidade definida</p></div><label className="table-search"><Search size={14} /><input aria-label="Buscar na equipe" placeholder="Buscar empregado ou projeto..." value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label></div><div className="table-scroll"><table className="sales-table"><thead><tr><th aria-sort={sort === 'id' ? descending ? 'descending' : 'ascending' : 'none'}><Button variant="ghost" size="sm" onClick={() => sortBy('id')}>Empregado<ArrowDownUp size={11} /></Button></th><th>Departamento</th><th>Sexo</th><th className="numeric" aria-sort={sort === 'salary' ? descending ? 'descending' : 'ascending' : 'none'}><Button variant="ghost" size="sm" onClick={() => sortBy('salary')}>Salário (u.m.)<ArrowDownUp size={11} /></Button></th><th className="numeric" aria-sort={sort === 'dependents' ? descending ? 'descending' : 'ascending' : 'none'}><Button variant="ghost" size="sm" onClick={() => sortBy('dependents')}>Dependentes<ArrowDownUp size={11} /></Button></th><th className="numeric" aria-sort={sort === 'hours' ? descending ? 'descending' : 'ascending' : 'none'}><Button variant="ghost" size="sm" onClick={() => sortBy('hours')}>Horas<ArrowDownUp size={11} /></Button></th><th>Projetos</th></tr></thead><tbody>{tableRows.slice(safePage*5, safePage*5+5).map(e => <tr key={e.id}><td><span className="product-cell"><span className="product-letter"><Users size={13} /></span>{e.id}</span></td><td>{e.department}</td><td>{e.sex}</td><td className="numeric">{number(e.salary)}</td><td className="numeric">{e.dependents}</td><td className="numeric">{number(e.hours)} h</td><td>{e.projects.join(', ') || '—'}</td></tr>)}{!tableRows.length && <tr><td colSpan={7} className="empty-state">Nenhum empregado encontrado.</td></tr>}</tbody></table></div><div className="table-footer"><span>{tableRows.length ? `${safePage*5+1}–${Math.min(safePage*5+5,tableRows.length)} de ${tableRows.length}` : '0 resultados'}</span><div className="flex items-center gap-3"><Button size="icon" variant="outline" aria-label="Página anterior" disabled={safePage === 0} onClick={() => setPage(safePage-1)}><ChevronLeft /></Button><span>{safePage+1} / {pageCount}</span><Button size="icon" variant="outline" aria-label="Próxima página" disabled={safePage >= pageCount-1} onClick={() => setPage(safePage+1)}><ChevronRight /></Button></div></div></section>
    <footer className="footer"><span>atlas. <span className="mx-2">/</span> Recursos Humanos</span><span>Registros, salários e alocações simulados · Referência: DIO Santander · Sem histórico temporal</span></footer>
  </DashboardShell>;
}