import { useMemo, useState } from 'react';
import { DashboardShell } from '@/components/dashboard-shell';
import { Link } from '@tanstack/react-router';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { BarChart3, LayoutDashboard, Package, Globe2, Download, RotateCcw, ChevronRight, ChevronLeft, ArrowUpRight, DollarSign, TrendingUp, ShoppingBag, Percent, CalendarDays, Search, Building2, SlidersHorizontal, ArrowDownUp, ArrowRight, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { categories, regions, months, initialFilters, filterSales, total, groupSales, money, compact, number, percent, periodLabels, type Filters, type Sale } from '@/lib/sales-data';

type View = 'overview' | 'products' | 'regions';
const colors = ['var(--chart-1)', 'var(--chart-2)', 'var(--chart-3)', 'var(--chart-4)', 'var(--chart-5)'];
const titles: Record<View, string> = { overview: 'Visão geral de vendas', products: 'Análise de produtos', regions: 'Desempenho por região' };
function FilterSelect({ label, value, options, onChange, year = false }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void; year?: boolean }) {
  return <div className={`filter ${year ? 'filter-year' : ''}`}><label>{label === 'Período' ? <CalendarDays size={12} /> : label === 'Região' ? <Globe2 size={12} /> : label === 'Categoria' ? <SlidersHorizontal size={12} /> : null}{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="filter-trigger"><SelectValue /></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
function ChartTip({ active, payload, label }: { active?: boolean; payload?: { name?: string; value?: number; payload?: { name?: string } }[]; label?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="chart-tip"><p>{label || payload[0]?.payload?.name}</p>{payload.map((p,i) => <strong key={i}>{p.name}: {money(p.value ?? 0)}</strong>)}</div>;
}
function exportCsv(rows: Sale[]) {
  const header = 'Ano;Mês;Produto;Categoria;Região;Unidades;Vendas USD;Custos USD;Descontos USD;Lucro USD';
  const content = '\uFEFF' + [header, ...rows.map(r => [r.year, months[r.month], r.product, r.category, r.region, r.units, r.sales, r.cogs, r.discounts, r.profit].join(';'))].join('\n');
  const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' }));
  const a = document.createElement('a'); a.href = url; a.download = 'atlas-vendas.csv'; a.click(); URL.revokeObjectURL(url);
}
export function SalesDashboard({ view = 'overview' }: { view?: View }) {
  const [filters, setFilters] = useState<Filters>(initialFilters);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const [sort, setSort] = useState<'sales' | 'profit' | 'units'>('sales');
  const [descending, setDescending] = useState(true);
  const [metric, setMetric] = useState<'sales' | 'profit'>('sales');
  const [exported, setExported] = useState(false);
  const update = (key: keyof Filters, value: string) => { setFilters(f => ({ ...f, [key]: value })); setPage(0); };
  const rows = useMemo(() => filterSales(filters), [filters]);
  const sums = total(rows), previousRows = filterSales(filters, Number(filters.year) - 1), previous = total(previousRows);
  const productGroups = groupSales(rows, 'product'), categoryGroups = groupSales(rows, 'category'), regionGroups = groupSales(rows, 'region');
  const timeline = months.map((name, month) => ({ name, ...total(rows.filter(r => r.month === month)), previous: total(previousRows.filter(r => r.month === month))[metric] })).filter((_, m) => filters.period === 'year' || (filters.period === 'h1' ? m < 6 : filters.period === 'h2' ? m >= 6 : m >= 9));
  const tableGroups = view === 'regions' ? regionGroups : productGroups;
  const filteredTable = tableGroups.filter(r => r.name.toLowerCase().includes(search.toLowerCase())).sort((a,b) => (descending ? -1 : 1) * (a[sort] - b[sort]));
  const pageCount = Math.max(1, Math.ceil(filteredTable.length / 5));
  const safePage = Math.min(page, pageCount - 1);
  const tableRows = filteredTable.slice(safePage * 5, safePage * 5 + 5);
  const comparison = (current: number, prior: number, margin = false) => prior ? (margin ? `${(current - prior).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} p.p.` : percent((current / prior - 1) * 100)) : '—';
  const metricCards = [
    { label: 'Receita total', value: compact(sums.sales), current: sums.sales, prior: previous.sales, icon: DollarSign },
    { label: 'Lucro bruto', value: compact(sums.profit), current: sums.profit, prior: previous.profit, icon: TrendingUp },
    { label: 'Unidades vendidas', value: number(sums.units), current: sums.units, prior: previous.units, icon: ShoppingBag },
    { label: 'Margem de lucro', value: percent(sums.margin), current: sums.margin, prior: previous.margin, icon: Percent, margin: true },
  ];
  const sortBy = (key: typeof sort) => { if (sort === key) setDescending(d => !d); else { setSort(key); setDescending(true); } setPage(0); };
  const countryCodes: Record<string,string> = { 'Estados Unidos': 'US', 'Canadá': 'CA', 'França': 'FR', 'Alemanha': 'DE', 'México': 'MX' };
  return <DashboardShell view={view}>
        <div className="page-heading"><div><h1>{titles[view]}</h1><p className="subtitle">{periodLabels[filters.period]} de {filters.year} <span className="mx-2">·</span> {filters.region === 'all' ? 'Todas as regiões' : filters.region}</p></div><div className="page-actions flex gap-2"><Button variant="outline" className="action-button" onClick={() => { setFilters(initialFilters); setSearch(''); setPage(0); }}><RotateCcw />Redefinir</Button><Button className="action-button" onClick={() => { exportCsv(rows); setExported(true); setTimeout(() => setExported(false), 2500); }}>{exported ? <Check /> : <Download />}{exported ? 'Exportado' : 'Exportar CSV'}</Button></div></div>
        <div className="filters">
          <FilterSelect label="Ano" year value={filters.year} options={['2025','2024'].map(y => ({ value: y, label: y }))} onChange={v => update('year',v)} />
          <FilterSelect label="Período" value={filters.period} options={Object.entries(periodLabels).map(([value,label]) => ({value,label}))} onChange={v => update('period',v)} />
          <FilterSelect label="Categoria" value={filters.category} options={[{value:'all',label:'Todas as categorias'}, ...categories.map(c => ({value:c,label:c}))]} onChange={v => update('category',v)} />
          <FilterSelect label="Região" value={filters.region} options={[{value:'all',label:'Todas as regiões'}, ...regions.map(r => ({value:r,label:r}))]} onChange={v => update('region',v)} />
        </div>
        <div className="kpis">{metricCards.map(k => <article className="metric-card" key={k.label}><div className="metric-top">{k.label}<span className="metric-icon"><k.icon size={15} /></span></div><div className="metric-value">{k.value}</div><div className="metric-bottom"><span className="change">{k.prior > 0 && <ArrowUpRight size={11} />}{comparison(k.current,k.prior,k.margin)}</span><span>{k.prior ? `vs. ${Number(filters.year)-1}` : 'Sem comparação anterior'}</span></div></article>)}</div>
        <div className="chart-grid">
          <section className="chart-section"><div className="section-heading"><div><h2>{view === 'products' ? 'Receita por produto' : view === 'regions' ? 'Receita por região' : 'Evolução das vendas'}</h2><p className="section-meta">{view === 'overview' ? 'Comparativo mensal · US$' : 'Receita total no período · US$'}</p></div>{view === 'overview' && <div className="flex gap-1"><Button size="sm" variant={metric === 'sales' ? 'secondary' : 'ghost'} onClick={() => setMetric('sales')}>Receita</Button><Button size="sm" variant={metric === 'profit' ? 'secondary' : 'ghost'} onClick={() => setMetric('profit')}>Lucro</Button></div>}</div>
            <div className="chart-container"><ResponsiveContainer width="100%" height="100%">{view === 'overview' ? <AreaChart data={timeline} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="sales-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.28} /><stop offset="100%" stopColor="var(--primary)" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="name" tick={{ fill:'var(--muted-foreground)', fontSize:10 }} axisLine={false} tickLine={false} dy={8} /><YAxis tickFormatter={v => `${(v/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`} tick={{ fill:'var(--muted-foreground)', fontSize:10 }} axisLine={false} tickLine={false} /><Tooltip content={<ChartTip />} /><Area type="monotone" dataKey="previous" name={String(Number(filters.year)-1)} stroke="var(--chart-3)" strokeWidth={1.5} strokeDasharray="5 5" fill="transparent" isAnimationActive={false} /><Area type="monotone" dataKey={metric} name={filters.year} stroke="var(--primary)" strokeWidth={2.5} fill="url(#sales-fill)" isAnimationActive={false} /></AreaChart> : <BarChart data={view === 'products' ? productGroups : regionGroups} layout="vertical" margin={{ top:0, right:10, left:10, bottom:0 }}><CartesianGrid stroke="var(--border)" horizontal={false} strokeDasharray="3 5" /><XAxis type="number" tickFormatter={v => `${Math.round(v/1e6)} mi`} tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={95} tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} /><Tooltip content={<ChartTip />} cursor={{fill:'var(--muted)'}} /><Bar dataKey="sales" name="Receita" fill="var(--primary)" radius={[0,3,3,0]} barSize={18} isAnimationActive={false} /></BarChart>}</ResponsiveContainer></div>
            {view === 'overview' && <div className="flex justify-center gap-5 mt-3"><span className="chart-key"><i />{filters.year}</span><span className="chart-key secondary"><i />{Number(filters.year)-1}</span></div>}
          </section>
          <section className="chart-section"><div className="section-heading"><div><h2>Vendas por categoria</h2><p className="section-meta">Participação na receita total</p></div><SlidersHorizontal size={15} className="text-muted-foreground" /></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categoryGroups} dataKey="sales" nameKey="name" innerRadius={54} outerRadius={73} paddingAngle={3} stroke="none" isAnimationActive={false} onClick={entry => update('category', entry.name)} className="cursor-pointer">{categoryGroups.map((g,i) => <Cell key={g.name} fill={colors[i%colors.length]} />)}</Pie><Tooltip content={<ChartTip />} /></PieChart></ResponsiveContainer><div className="donut-label"><strong>{categoryGroups.length}</strong><span>{categoryGroups.length === 1 ? 'categoria' : 'categorias'}</span></div></div><div className="segment-legend">{categoryGroups.map((g,i) => <Button variant="ghost" className="legend-item" key={g.name} onClick={() => update('category', filters.category === g.name ? 'all' : g.name)}><span className="legend-name"><i className={`dot dot-${i}`} />{g.name}</span><span className="text-foreground">{percent(g.sales/sums.sales*100)}</span></Button>)}</div></section>
          <section className="chart-section"><div className="section-heading"><div><h2>{view === 'products' ? 'Lucro por produto' : 'Produtos em destaque'}</h2><p className="section-meta">{view === 'products' ? 'Lucro bruto no período · US$' : 'Receita por produto · US$'}</p></div>{view !== 'products' && <Button asChild size="sm" variant="ghost"><Link to="/produtos" aria-label="Ver análise de produtos"><ArrowUpRight /></Link></Button>}</div><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={productGroups} margin={{top:10,right:5,left:-12,bottom:0}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="name" tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} dy={5} /><YAxis tickFormatter={v => `${Math.round(v/1e6)} mi`} tick={{fill:'var(--muted-foreground)',fontSize:10}} axisLine={false} tickLine={false} /><Tooltip content={<ChartTip />} cursor={{fill:'var(--muted)'}} /><Bar dataKey={view === 'products' ? 'profit' : 'sales'} name={view === 'products' ? 'Lucro' : 'Receita'} fill="var(--primary)" radius={[4,4,0,0]} maxBarSize={37} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></section>
          <section className="chart-section"><div className="section-heading"><div><h2>Desempenho regional</h2><p className="section-meta">Distribuição geográfica das vendas</p></div><Globe2 size={15} className="text-muted-foreground" /></div><div className="region-list">{regionGroups.map(g => <div key={g.name}><div className="region-top"><span className="region-name"><span className="country-code">{countryCodes[g.name]}</span>{g.name}</span><span className="region-value">{compact(g.sales)}<span>{Math.round(g.sales/sums.sales*100)}%</span></span></div><progress className="region-progress" value={g.sales} max={sums.sales} aria-label={`Participação de ${g.name}`} /></div>)}</div></section>
        </div>
        <section className="table-section"><div className="section-heading"><div><h2>{view === 'regions' ? 'Detalhamento por região' : 'Detalhamento de vendas'}</h2><p className="section-meta">Consolidado por {view === 'regions' ? 'país' : 'produto'} · {number(rows.length)} registros no período</p></div><label className="table-search"><Search size={14} /><input aria-label="Buscar na tabela" placeholder={view === 'regions' ? 'Buscar região...' : 'Buscar produto...'} value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} /></label></div><div className="table-scroll"><table className="sales-table"><thead><tr><th>{view === 'regions' ? 'Região' : 'Produto'}</th><th className="numeric"><Button variant="ghost" size="sm" onClick={() => sortBy('sales')}>Receita <ArrowDownUp size={11} /></Button></th><th className="numeric"><Button variant="ghost" size="sm" onClick={() => sortBy('profit')}>Lucro bruto <ArrowDownUp size={11} /></Button></th><th className="numeric"><Button variant="ghost" size="sm" onClick={() => sortBy('units')}>Unidades <ArrowDownUp size={11} /></Button></th><th className="numeric">Descontos</th><th className="numeric">Margem</th></tr></thead><tbody>{tableRows.map(g => <tr key={g.name}><td><span className="product-cell"><span className="product-letter">{g.name.slice(0,1)}</span>{g.name}</span></td><td className="numeric">{money(g.sales)}</td><td className="numeric">{money(g.profit)}</td><td className="numeric">{number(g.units)}</td><td className="numeric text-muted-foreground">{money(g.discounts)}</td><td className="numeric"><span className="margin-badge">{percent(g.margin)}</span></td></tr>)}{!tableRows.length && <tr><td colSpan={6} className="empty-state">Nenhum resultado para “{search}”.</td></tr>}</tbody></table></div><div className="table-footer"><span>{filteredTable.length ? `${safePage*5+1}–${Math.min(safePage*5+5,filteredTable.length)} de ${filteredTable.length}` : '0 resultados'}</span><div className="flex items-center gap-3"><Button size="icon" variant="outline" aria-label="Página anterior" disabled={safePage === 0} onClick={() => setPage(safePage-1)}><ChevronLeft /></Button><span>{safePage+1} / {pageCount}</span><Button size="icon" variant="outline" aria-label="Próxima página" disabled={safePage >= pageCount-1} onClick={() => setPage(safePage+1)}><ChevronRight /></Button></div></div></section>
        <footer className="footer"><span>atlas. <span className="mx-2">/</span> Sales Intelligence</span><span>Dados simulados · Moeda demonstrativa: USD · Referência: Sales Report</span></footer>
  </DashboardShell>;
}
